#!/usr/bin/env python3
"""
06_capture_catalog.py — Catalog PDP fixture capture via Cloak headed browser.

Drives Cloakbrowser (stealth Chromium) to each of 10 AR catalog hosts,
captures raw HTML to tests/fixtures/catalog/<host_slug>/product-NN.html,
appends per-fixture rows to tests/fixtures/catalog/MANIFEST.md.

References:
  01-RESEARCH.md §Pattern 5 (lines 511-530) — target host list
  01-RESEARCH.md §Pattern 1 (lines 267-322) — Cloak launch/context idiom
  01-RESEARCH.md §Anti-Patterns (lines 711-714) — throttle, IP-block protection
  01-03-PLAN.md Task 1 — acceptance criteria + VISIT-08 invariant

Exit codes:
  0 — ≥10 fixtures captured successfully
  1 — fewer than 10 fixtures captured (partial run — re-invoke with different URL list to top up)
  2 — pre-flight VISIT-08 violation or missing catalog_urls.txt

VISIT-08 invariant: NEVER fetch *.mercadolibre.* URLs.
D8 invariant: Singleton Browser + ephemeral new_context() per host (see Cloak issue #331).
D6 invariant: asyncio.run() only. # FORBIDDEN: uvloop
Throttle: ≥30s between hosts (RESEARCH §Pitfall 5).
"""

import asyncio
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── LD_LIBRARY_PATH for WSL2 (libnspr4/libnss3 — from 01-01 deviation fix) ──
_local_libs = Path.home() / "local-libs" / "usr" / "lib" / "x86_64-linux-gnu"
if _local_libs.exists():
    os.environ["LD_LIBRARY_PATH"] = (
        str(_local_libs) + ":" + os.environ.get("LD_LIBRARY_PATH", "")
    )

# ── Cloak import path discovery (Pitfall 1: 0.3.31 exports launch_async directly) ─
try:
    import cloakbrowser
    if not hasattr(cloakbrowser, "launch_async"):
        raise ImportError("launch_async not found in cloakbrowser — wrong version?")
except ImportError as e:
    print(f"ERROR: cloakbrowser not installed or wrong version: {e}", file=sys.stderr)
    print("Run: uv pip install cloakbrowser==0.3.31", file=sys.stderr)
    sys.exit(1)

# ── Constants ────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
CATALOG_URLS_FILE = SCRIPT_DIR / "catalog_urls.txt"
FIXTURES_DIR = Path(__file__).parent.parent.parent / "tests" / "fixtures" / "catalog"
MANIFEST_FILE = FIXTURES_DIR / "MANIFEST.md"

THROTTLE_SECONDS = 30  # ≥30s between hosts (RESEARCH §Pitfall 5 line 768)
GOTO_TIMEOUT_MS = 25_000  # 25s page load timeout

MELI_PATTERN = re.compile(r"mercadolibre\.", re.IGNORECASE)


def load_urls(path: Path) -> list[str]:
    """Load URLs from file, stripping comments and blanks."""
    urls = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        urls.append(line)
    return urls


def url_to_slug(url: str) -> str:
    """Convert a URL to a filesystem-safe host slug.

    e.g. 'https://www.falabella.com.ar/...' → 'falabella_com_ar'
         'https://martinmorris.ar/...' → 'martinmorris_ar'
    """
    # Extract host
    m = re.match(r"https?://(?:www\.)?([^/]+)", url)
    if not m:
        return "unknown"
    host = m.group(1)
    # Replace dots/hyphens with underscores
    slug = re.sub(r"[.\-]", "_", host)
    return slug


async def capture_one(browser, url: str, fixture_path: Path) -> dict:
    """Capture raw HTML from one URL using a fresh ephemeral context.

    Returns a result dict with keys: url, status, byte_count, error.
    D8 invariant: fresh new_context() per call, closed in finally.
    """
    ctx = None
    try:
        ctx = await browser.new_context(
            locale="es-AR",
            timezone_id="America/Argentina/Buenos_Aires",
            viewport={"width": 1366, "height": 768},
        )
        page = await ctx.new_page()
        resp = await page.goto(url, wait_until="domcontentloaded", timeout=GOTO_TIMEOUT_MS)
        status = resp.status if resp else 0
        html = await page.content()
        fixture_path.parent.mkdir(parents=True, exist_ok=True)
        fixture_path.write_text(html, encoding="utf-8")
        return {"url": url, "status": status, "byte_count": len(html.encode("utf-8")), "error": None}
    except Exception as e:
        err_msg = f"{type(e).__name__}: {str(e)[:120]}"
        return {"url": url, "status": 0, "byte_count": 0, "error": err_msg}
    finally:
        if ctx:
            try:
                await ctx.close()
            except Exception:
                pass


def append_manifest_row(
    host_slug: str,
    url: str,
    capture_date: str,
    byte_count: int,
    status: int,
    error: str | None,
) -> None:
    """Append one fixture row to MANIFEST.md, creating the file+header if absent."""
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

    if not MANIFEST_FILE.exists():
        header = (
            "# Catalog Fixture Manifest\n\n"
            "Generated by `scripts/spike/06_capture_catalog.py`. "
            "Classification columns filled by `08_extruct_classifier.py`.\n\n"
            "| host_slug | url | capture_date | byte_count | http_status | classification | extracted_price | extracted_name |\n"
            "|---|---|---|---|---|---|---|---|\n"
        )
        MANIFEST_FILE.write_text(header, encoding="utf-8")

    if error:
        classification = "load_failed"
        note = f" <!-- error: {error[:80]} -->"
    elif byte_count < 10_000:
        classification = "load_failed"
        note = " <!-- tiny response — likely 403 or login wall -->"
    else:
        classification = "TBD"
        note = ""

    row = (
        f"| {host_slug} | {url[:80]} | {capture_date} | {byte_count} | "
        f"{status} | {classification} | TBD | TBD |{note}\n"
    )
    with open(MANIFEST_FILE, "a", encoding="utf-8") as f:
        f.write(row)


async def main() -> int:
    # ── Load and validate URL list ───────────────────────────────────────────
    if not CATALOG_URLS_FILE.exists():
        print(
            f"ERROR: {CATALOG_URLS_FILE} not found — see plan task 1 sub-step A",
            file=sys.stderr,
        )
        print("Run: see scripts/spike/README.md §Catalog URLs", file=sys.stderr)
        return 2

    urls = load_urls(CATALOG_URLS_FILE)
    if len(urls) < 10:
        print(
            f"ERROR: need ≥10 URLs in {CATALOG_URLS_FILE.name}, found {len(urls)}",
            file=sys.stderr,
        )
        return 2

    # ── VISIT-08 pre-flight: abort if ANY URL is a MELI host ────────────────
    violations = [u for u in urls if MELI_PATTERN.search(u)]
    if violations:
        print(
            "ERROR: VISIT-08 violation — mercadolibre URL(s) detected:\n"
            + "\n".join(f"  {v}" for v in violations),
            file=sys.stderr,
        )
        print("Remove all mercadolibre.* URLs from catalog_urls.txt", file=sys.stderr)
        return 1

    print(f"[06_capture_catalog] Loaded {len(urls)} URLs (VISIT-08 clean)")

    # ── Launch Cloak browser (singleton — D8 invariant) ─────────────────────
    browser = None
    captured_count = 0
    capture_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    try:
        browser = await cloakbrowser.launch_async(
            headless=True,
            args=["--no-sandbox", "--disable-dev-shm-usage"],
        )
        print(f"[06_capture_catalog] Browser launched: {browser}")

        # ── Per-host capture loop ────────────────────────────────────────────
        seen_hosts: set[str] = set()

        for idx, url in enumerate(urls, start=1):
            slug = url_to_slug(url)

            # Per-host cap: never visit the same host more than once
            if slug in seen_hosts:
                print(f"[{idx:02d}] SKIP: {slug} already captured (per-host cap)")
                continue
            seen_hosts.add(slug)

            fixture_path = FIXTURES_DIR / slug / "product-01.html"
            print(f"[{idx:02d}] Capturing {slug} → {url[:80]}")

            result = await capture_one(browser, url, fixture_path)

            kb = result["byte_count"] / 1024
            if result["error"]:
                print(f"[{idx:02d}]   ERROR: {result['error']}")
            elif result["byte_count"] < 50_000:
                print(
                    f"[{idx:02d}]   WARNING: tiny response {kb:.1f}KB — possible 403/login wall "
                    f"(status={result['status']})"
                )
            else:
                print(
                    f"[{idx:02d}]   OK: {kb:.1f}KB (status={result['status']})"
                )
                captured_count += 1

            append_manifest_row(
                host_slug=slug,
                url=url,
                capture_date=capture_date,
                byte_count=result["byte_count"],
                status=result["status"],
                error=result["error"],
            )

            # Throttle: ≥30s between hosts (RESEARCH §Pitfall 5 line 768)
            if idx < len(urls):
                print(f"[{idx:02d}]   Throttle: sleeping {THROTTLE_SECONDS}s...")
                await asyncio.sleep(THROTTLE_SECONDS)

    finally:
        if browser:
            try:
                await browser.close()
                print("[06_capture_catalog] Browser closed cleanly")
            except Exception as e:
                print(f"[06_capture_catalog] Browser close error (non-fatal): {e}")

    # ── Final tally ──────────────────────────────────────────────────────────
    total_html = list(FIXTURES_DIR.rglob("*.html"))
    total_count = len(total_html)
    print(f"\n[06_capture_catalog] Done. Total fixtures on disk: {total_count}")
    print(f"[06_capture_catalog] Captured successfully this run: {captured_count}")

    if total_count >= 10:
        print("[06_capture_catalog] AC-4 satisfied: ≥10 fixtures captured")
        return 0
    else:
        print(
            f"[06_capture_catalog] WARN: only {total_count} fixtures — need ≥10 for AC-4",
            file=sys.stderr,
        )
        return 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
